Compiler bug fixes
source-academy/java-slang pull request #52
Opened 2024-04-13 09:48 UTC by 1001mei

2024-04-14 23:11 UTC, martin-henz requested changes
The function `addLocInfo` is duplicated. You may be able to avoid the duplication by including it as a dependency in the call of `peggy.generate`.

2024-10-07 04:16 UTC, AprupKale approved these changes
lgtm 👍

2024-10-08 05:17 UTC, AprupKale approved these changes

2024-10-08 07:06 UTC, martin-henz approved these changes
ok now

2024-10-08 07:07 UTC, merged